# Stage 1
FROM node:20-bookworm-slim AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

# Stage 2
FROM node:20-bookworm-slim AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_BASE_API_ENDPOINT
ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_LOGIN_ENDPOINT
ARG NEXT_PUBLIC_REGISTER_ENDPOINT
ARG NEXT_PUBLIC_LOGOUT_ENDPOINT
ARG NEXT_PUBLIC_REFRESH_ENDPOINT
ARG NEXT_PUBLIC_USER_PROFILE_ENDPOINT
ARG NEXT_PUBLIC_DEVICES_ENDPOINT
ARG NEXT_PUBLIC_DEVICE_STATUS_ENDPOINT
ARG NEXT_PUBLIC_INCIDENTS_ENDPOINT
ARG NEXT_PUBLIC_GATE_LOGS_ENDPOINT
ARG NEXT_PUBLIC_GATE_LOGS_EXPORT_ENDPOINT
ARG NEXT_PUBLIC_USE_MOCK_AUTH

ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_PUBLIC_BASE_API_ENDPOINT=$NEXT_PUBLIC_BASE_API_ENDPOINT
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_LOGIN_ENDPOINT=$NEXT_PUBLIC_LOGIN_ENDPOINT
ENV NEXT_PUBLIC_REGISTER_ENDPOINT=$NEXT_PUBLIC_REGISTER_ENDPOINT
ENV NEXT_PUBLIC_LOGOUT_ENDPOINT=$NEXT_PUBLIC_LOGOUT_ENDPOINT
ENV NEXT_PUBLIC_REFRESH_ENDPOINT=$NEXT_PUBLIC_REFRESH_ENDPOINT
ENV NEXT_PUBLIC_USER_PROFILE_ENDPOINT=$NEXT_PUBLIC_USER_PROFILE_ENDPOINT
ENV NEXT_PUBLIC_DEVICES_ENDPOINT=$NEXT_PUBLIC_DEVICES_ENDPOINT
ENV NEXT_PUBLIC_DEVICE_STATUS_ENDPOINT=$NEXT_PUBLIC_DEVICE_STATUS_ENDPOINT
ENV NEXT_PUBLIC_INCIDENTS_ENDPOINT=$NEXT_PUBLIC_INCIDENTS_ENDPOINT
ENV NEXT_PUBLIC_GATE_LOGS_ENDPOINT=$NEXT_PUBLIC_GATE_LOGS_ENDPOINT
ENV NEXT_PUBLIC_GATE_LOGS_EXPORT_ENDPOINT=$NEXT_PUBLIC_GATE_LOGS_EXPORT_ENDPOINT
ENV NEXT_PUBLIC_USE_MOCK_AUTH=$NEXT_PUBLIC_USE_MOCK_AUTH

RUN npm run build

# Stage 3
FROM node:20-bookworm-slim AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000

COPY --from=builder --chown=node:node /app/.next/standalone ./
COPY --from=builder --chown=node:node /app/.next/static ./.next/static
COPY --from=builder --chown=node:node /app/public ./public

EXPOSE 3000

USER node

CMD ["node", "server.js"]
