services:
  frontend:
    image: ghcr.io/ngocphuoc2206/metro-station-management-frontend:latest
    container_name: metro-management-ticket-frontend
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "${APP_PORT:-3000}:3000"
    restart: unless-stopped
